server:
  port: ${server-port:9031}

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
                        classpath:/static/,classpath:/public/,file:${web.file.read-path}

web:
  file:
    read-path: /data/projectLog/
